### ISSUE TITLE
after OAuth2 - error due to invalid/expired State-Token

### ISSUE THREAD

**Issue by thebuba** [rcmdnk/Withings-gas#1]
I get an error message after authorization on the Withingswebsite (OAuth2) - it says "the State-Token is invalid or expired. Try again". I can't seem to figure out why it's not running correctly, I am assuming there are parameters missing (like the state-token obviously) - but it could also be a forwarding problem with e.g. the initialization of the OAuth2.

@rcmdnk I made a PDF describing my problem, let me know if you happen to have any chance to take a look at it :-)

--
so this is my first ever contribution here, kindly let me know whether I forgot something or did anything wrong :-)

**Comment by rcmdnk** [comment]
Thank you for the feedback.
For me, the script is still working. 

How do you set up your App Script project?
Making from Google Spreadsheet or directly?

If you create the project from Google Spreadsheet,
which functions have you tried:
* Measure.gs/height or/and body
* Sleep.gs/sleepSummary

Are you sure with CLIENT_ID, CLIENT_SECRET, and EMAIL?

If you put codes as the library and call it from another project, it may fail:

* https://stackoverflow.com/questions/23867189/how-to-correctly-construct-state-tokens-for-callback-urls-in-managed-libraries

Followings may not be related to your issue, but some may help you. 
* https://github.com/googleworkspace/apps-script-oauth2/issues/74
* https://github.com/googleworkspace/apps-script-oauth1/issues/2

**Comment by thebuba** [comment]
thank you for the quick reply.

It's via google spreadsheet
and
I used the body function.
However the problem is the request function, seems like I can't be authorized - can't authorize myself. Also yes, I am sure with CLIENT-ID, CLIENT-SECRET and EMAIL

So basically I just copied your code, adjusted it (CLIENT-ID etc.) and the only library I am using is the OAuth2.


I attached a PDF showing my steps and problems. I hope this might helps. I really appreciate your support!
[commenterrormessageStateToken.pdf](https://github.com/rcmdnk/Withings-gas/files/7775716/commenterrormessageStateToken.pdf)

**Comment by rcmdnk** [comment]
I think you are here, right?

https://github.com/rcmdnk/Withings-gas/blob/148b7968fd3d8a0f35514be80fd599b9c49e3ef6/Withings.gs#L11

You got **AuthorizationUrl** in the error message and tried to open it.
First you saw the sign in page to my account of Withings.
You are asked to allow the app.
After pushing `Allow` button, you saw the message `the State-Token is invalid or expired. Try again.`

If so, it should be different from the problem of `Access Token`.
`Access Token` is obtained at https://github.com/rcmdnk/Withings-gas/blob/148b7968fd3d8a0f35514be80fd599b9c49e3ef6/Withings.gs#L24
which is executed only when authorization was succeeded.

**Comment by rcmdnk** [comment]
Can you try followings?

* Go to 
https://account.withings.com/partner/dashboard_oauth2

* Create application (I think you already have),
and edit callback url as `https://localhost`.

* Then open following url (replace `<Your Client ID>` with your client ID):
`https://account.withings.com/oauth2_user/authorize2?response_type=code&client_id=<Your Client ID>&scope=user.metrics,user.activity&redirect_uri=https://localhost&state=dev`

* Then allow the app.
It will show access failure but you can see the URL in the browser's address bar like:
`https://localhost/?code=<CODE>&state=dev`
If the URL is like this, it is succeeded and you can go to get the Access Token with this `CODE`.

**Comment by rcmdnk** [comment]
The message ` the State-Token is invalid or expired. Try again.` seems related to the `state` parameter in **AuthorizationUrl**.

In the above simple example, the `state` parameter can be arbitrarily words.

In Google's case, it seems the parameter is checked, and somehow your `state` parameter in the **AuthorizationUrl** is different from the actual `state` saved in the Apps Script...?

**Comment by thebuba** [comment]
thank you so much for the feedback! 

I followed your steps from the second reply, this worked well - however now I have the code, but no clue how to get the access token

Also I do believe the state-token is different, because it seems like it is not in the body of my post request as withings requires.

thank you so much!
looking forward to your help :-)

**Comment by rcmdnk** [comment]
If you can run commands in a terminal (if you can use `curl` command), you can get information like this:

* Open URL: `https://account.withings.com/oauth2_user/authorize2?response_type=code&client_id=<Your Client ID>&scope=user.metrics,user.activity&redirect_uri=https://localhost&state=dev` and get `code`.
* Run the following command in a terminal:

        curl --data 'grant_type=authorization_code&client_id=<CLIDENT ID>&client_secret=<CLIENT SECRET>&redirect_uri=https://localhost&code=<CODE>' 'https://account.withings.com/oauth2/token'

    * Note: `CODE` is valid only 30 sec, so you should prepare the above command with empty `<CODE>` before opening the above URL, get `CODE`, copy and paste `CODE`, and run the command
    * If you are too late, you will get:
         * `{"errors":[{"message":"invalid_grant: Invalid Params: invalid code"}]}`
    * If you succeeded, you will get like:
         * `{"access_token":"<ACCESS TOKEN>","expires_in":10800,"token_type":"Bearer","scope":"user.metrics,user.activity","refresh_token":"<REFRESH TOKEN>","userid":"<USER ID>"}`
        
 * Now you have `access_token`. Then, get information via API:

        curl 'https://wbsapi.withings.net/measure?action=getmeas&access_token=<ACCESS TOKEN>&meastype=1&category=1&startdate=1609459200&enddate=1640995200'

    * `meastype=1`: Weight, `category=1`: Real measures
        * [Measure - Getmeas](https://developer.withings.com/api-reference/#operation/measure-getmeas)
    * `1609459200` and `1640995200` are `2021/01/01 00:00:00` and `2022/01/01 00:00:00` in the unix time, respectively.

**Comment by rcmdnk** [comment]
On the other hand,
I could reproduce your error with Apps Script by changing `code` characters.

So, there may be spaces in `code` when you pasted.
It is a long URL and there are a lot of line breaks in appearance, so it can be by accident (depending on the browser, language...?)

You can try to paste the URL in the notepad and check if it is correctly one line, then copy and paste it to the browser's address bar.

**Comment by thebuba** [comment]
thank you so much for the detailed reply.
I went ahead and did just like you recommended and timeise (30sec) it worked, however I get this error message: {"errors":[{"message":"invalid_grant: Wrong redirect_uri - Please use same as the one set to get authorization
code"}]}

Not sure why, everything is done accordingly to your guidance. Also my redirect_url is the same as my callback url
Please see below the scirpt, maybe you happen to notice what I did wrong :-)


STRING = str(input())
CLIENT_ID = "ID"
CLIENT_SECRET = "SECRET"
 
startWith = "code="
endWith = "&"
stringLength_Starter = len(startWith)
i_start = STRING.index(startWith)
tempSTRING = STRING[i_start+stringLength_Starter:]
i_finish = tempSTRING.index(endWith)
code = tempSTRING[:i_finish]
 
print()
stringToRunInCMD = f'curl --data "grant_type=authorization_code&client_id={CLIENT_ID}&client_secret={CLIENT_SECRET}&redirect_uri=https://localhost&code={code}" "https://account.withings.com/oauth2/token"'
print("String To run in CMD:")
print(stringToRunInCMD)
print()

**Comment by rcmdnk** [comment]
"errors":[{"message":"invalid_grant: Wrong redirect_uri - Please use same as the one set to get authorization code"}]

This means you set the wrong callback URI at https://account.withings.com/partner/dashboard_oauth2
It should be `https://localhost` in this case.

You can only set one callback URI on your account,
therefore you need to replace the callback URI for this test and switch back to Google Sheets' one once you finished the test.

**Comment by thebuba** [comment]
thanks! 
So using curl I was able to retrieve my data using the access token. This works for the callback-URI "localhost" and callback URI "script.google.com/macros/.... " - the only problem I seem to be left with is that it is still not working gsheets. Does it mean I send the wrong POST request to the callback URI when I use gsheets?

**Comment by rcmdnk** [comment]
Then, I think the `<code>` is wrong.

You get the URL with the `<code>` on Google App Script editor's error message
and it may have line breaks or extra spaces.

Could you please check by pasting the URL to the Notepad or any editors?

**Comment by thebuba** [comment]
thank you for all your patience. 
Now it seems to work.
However it was not extra spaces or line breaks, my problem was I am fairly new (as anyone can tell I guess) to this and I was running the function "body" in gsheets. No clue that the function can be run separately in script. Now that I am running it separately the auth-url is different. The state token is longer when run in the script and shorter when run in gsheets. With the missing characters, the state token is identified wrongly. 
However I don't understand why, but if run in the script it works - longer state token and authorization works and I can allow the app. 

Out of curiosity do you know why the token is different?
Also was I supposed to run this via script the whole time?

**Comment by rcmdnk** [comment]
Sorry for the late reply.

I could not reproduce your situation but I tested the following.

Such a `body` function calls some spreadsheets functions and sometimes it fails if you write the function in the cell of the spreadsheets.
(like `=body()`
in my case, it says:
`Exception: You do not have permission to call setSpreadsheetTimeZone（line 3`

If you want to 

If you set `button` on the sheets, and assign such a `body`, then it works.

Ref:
https://spreadsheet.dev/buttons-in-google-sheets

The first time you push the button, it shows an error and you can get the URL.
The code in the URL is correct and it works.
Then, you can run the script by pushing the button.

**Comment by rcmdnk** [comment]
`Measure/getMeas()` function returns values.
Then, you can use `=getMeas()` in the cell of the spreadsheets.
It will write 2 columns of DateTime and weight.

But if you call this function before the authorization,
it fails at line 15 in `Withings.gs`: \`
`Session.getActiveUser()` (Error: `You don't have permission`)

If you run the script in the app script once and get authorization, it works in the spreadsheets, too.
